// Code generated by mockery v1.0.0. DO NOT EDIT.

// @generated

package mocks

import mock "github.com/stretchr/testify/mock"

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// GetVolume provides a mock function with given fields:
func (_m *Manager) GetVolume() float64 {
	ret := _m.Called()

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// Play provides a mock function with given fields:
func (_m *Manager) Play() {
	_m.Called()
}

// SetVolume provides a mock function with given fields: _a0
func (_m *Manager) SetVolume(_a0 float64) (float64, error) {
	ret := _m.Called(_a0)

	var r0 float64
	if rf, ok := ret.Get(0).(func(float64) float64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(float64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
